version: '3.8'

services:
  middleware-loader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Expose port to localhost
    environment:
      - LOG_LEVEL=info
      - SERVICE_NAME=middleware-loader
      