version: '3.8'

services:
  gaia-connector:
    image: server-gaia-connector
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose port to localhost
    network_mode: host #Allow the container to access the host network
    environment:
      - LOG_LEVEL=info
      - SERVICE_NAME=gaia-connector
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=3306
      - DATABASE_NAME=gaia_connector
      - DATABASE_USERNAME=golde
      - DATABASE_PASSWORD=483777