version: '3.8'

services:
  middleware-loader:
    image: server-middleware-loader
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Expose port to localhost
    network_mode: host #Allow the container to access the host network
    environment:
      - LOG_LEVEL=info
      - SERVICE_NAME=middleware-loader
      - DATABASE_HOST=172.17.0.1
      - DATABASE_PORT=27017
      - DATABASE_NAME=middleware_loader
      - DATABASE_USERNAME=golde
      - DATABASE_PASSWORD=483777
    