gaia_introduction_sample = [
    "Who are you?",
    "What is your name?",
    "Can you introduce yourself?",
    "Tell me about yourself.",
    "What can you do?",
    "What is your purpose?",
    "What are your capabilities?",
    "What is your function?",
    "What is your role?",
    "What is your job?",
    "What is your mission?",
    "What is your goal?",
    "What is your objective?",
    "List your functions.",
    "What are your features?",
    "What are your abilities?",
    "What can you help me with?",
    "What can you do for me?",
    "How can you assist me?",
    "How can you help me?",
    "What can you do for me?",
    "What are your skills?",
    "What are your talents?",   
]

chitchat_sample = [
    "How are you?",
    "What is your favorite color?",
    "What is your favorite food?",
    "What is your favorite movie?",
    "What is your favorite book?",
    "What is your favorite music?",
    "Can you tell me a joke?",
    "What is your favorite hobby?",
    "What do you like to do in your free time?",
    "What is your favorite sport?",
    "Hello",
    "Hi",
    "How is the weather today?",
    "Tell me a story.",
    "Tell my a joke.",
    "What is the meaning of life?",
]

register_calendar_example_sample = [
    "I don't know how to tell you my day, how am I supposed to do that?",
    "Can you provide me an example of how to describe my day?",
    "I need help organizing my daily schedule, can you show me how?",
    "How do I tell you about my daily routine?",
    "Can you give me an example of a daily schedule?",
    "I want to register my daily activities, how should I describe them?",
    "What format should I use to tell you about my day?",
    "Can you show me how to structure my daily activities?",
    "I need to organize my day, can you help me with an example?",
    "How can I describe my daily routine to you?",
    "Can you provide a template for describing my day?",
    "I want to share my daily schedule, how should I format it?",
]