# model/tokenizer
model_name: "EleutherAI/gpt-j-6B"
tokenizer_name: "EleutherAI/gpt-j-6B"

# dataset
streaming: false
num_proc: 32
dataset_path: "../input/data/nomic_ai_parquet1.parquet_0.parquet"
max_length: 1024
batch_size: 32

# logging
seed: 42