version: '3.8'

services:
  work_optimization: 
    image: server-work-optimization
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    network_mode: "host"
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=golde
      - DB_PASSWORD=483777
      - DB_NAME=work_optimization
