gaia_introduction_sample = [
    "Who are you?",
    "What is your name?",
    "Can you introduce yourself?",
    "Tell me about yourself.",
    "What can you do?",
    "What is your purpose?",
    "What are your capabilities?",
    "What is your function?",
    "What is your role?",
    "What is your job?",
    "What is your mission?",
    "What is your goal?",
    "What is your objective?",
    "List your functions.",
    "What are your features?",
    "What are your abilities?",
    "What can you help me with?",
    "What can you do for me?",
    "How can you assist me?",
    "How can you help me?",
    "What can you do for me?",
    "What are your skills?",
    "What are your talents?",   
]

chitchat_sample = [
    "How are you?",
    "What is your favorite color?",
    "What is your favorite food?",
    "What is your favorite movie?",
    "What is your favorite book?",
    "What is your favorite music?",
    "Can you tell me a joke?",
    "What is your favorite hobby?",
    "What do you like to do in your free time?",
    "What is your favorite sport?",
    "Hello",
    "Hi",
    "How is the weather today?",
    "Tell me a story."
]

