# model/tokenizer
model_name: "EleutherAI/gpt-j-6B"
tokenizer_name: "EleutherAI/gpt-j-6B"
gradient_checkpointing: true
save_name: "GaiaGpt4all"

# dataset
streaming: false
num_proc: 32
dataset_path: "../input/data/nomic_ai_parquet1.parquet_0.parquet"
max_length: 1024
batch_size: 32

# train dynamics
lr: 2.0e-5
min_lr: 0
weight_decay: 0.0
eval_every: 500
eval_steps: 105
save_every: 500
log_grads_every: 100
output_dir: "../output/data/"
checkpoint: null
lora: false
warmup_steps: 500
num_epochs: 2

# logging
wandb: true
wandb_entity: "gaia"
wandb_project_name: "gaiagpt4all"
seed: 42