# Docker Compose configuration for Personal Task Manager using .env file
version: '3.8'

services:
  task-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./src/.env
    depends_on: []
